// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 12/4/2025, 12:04:08 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["/home/karyl/veep/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/karyl/veep/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/karyl/veep/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/karyl/veep/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/karyl/veep/plugins/**/*.{js,ts,mjs}","/home/karyl/veep/composables/**/*.{js,ts,mjs}","/home/karyl/veep/utils/**/*.{js,ts,mjs}","/home/karyl/veep/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/karyl/veep/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/home/karyl/veep/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/home/karyl/veep/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;